### ISSUE TITLE
Run-Time Check Failure #2 - 64-bit compilation

### ISSUE THREAD

**Issue by mediabuff** [AndreiMuntea/ALPC-Port#1]
Run-Time Check Failure #2 - Stack around the variable 'requiredSize' was corrupted.

in AlpcMessageAttributesInitialize

**Comment by AndreiMuntea** [comment]
Wow, can't believe I somehow missed this issue. 
I tested it on x86  only.
I just pushed a fix that should work on x64

**Comment by AndreiMuntea** [comment]
500e2d10aa81c343abc58496be5f3081cd56772f should fix it
